name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Permissions on mvnw
        run: chmod 755 ./mvnw

      - name: Build Application
        run: |
          ./mvnw clean package -e

      - name: Run Unit Tests
        run: |
          ./mvnw test

      - name: Run Application
        run: |
          java -jar ./target/*.jar --server.port=8080
